### ISSUE TITLE
Dustin Taylor’s Evaluation

### ISSUE THREAD

**Issue by taylordusting** [wderaad/RESTfulSkiPlanner#1]
Unfortunately, I have been unable to get the code up and running on my machine (OSX). However, after examining the README, and taking a look at your test code, the tests do appear to all be passing. So, perhaps I do not meet the system specifications to run the app, but it appears to working well! Nice job.

**Comment by wderaad** [comment]
Thanks for the evaluation, it looks like the latest commit snuck in a bunch of class files. I rolled back to the previous commit and it works for me on OSX as well now. Sorry about the inconvenience.
