### ISSUE TITLE
Ian Moore's Evaluation

### ISSUE THREAD

**Issue by Brefew** [wderaad/RESTfulSkiPlanner#2]
Unfriendly amount of files and difficult to navigate to look at the code. 
However, helpful readme file! Unable to get the code to work on my own machine, but it looks as though everything is well thought out and in order. Nice work!

**Comment by wderaad** [comment]
Thanks for the evaluation, it looks like the latest commit snuck in a bunch of class files. I rolled back to the previous commit so there should definitely be less files and it should work on your machine now. Sorry about the inconvenience.
