### ISSUE TITLE
Justin McBride's Evaluation

### ISSUE THREAD

**Issue by justinmcbride** [wderaad/RESTfulSkiPlanner#3]
I like your choice in trying a different architecture for the web service, rather than all the others. Unfortunately, it made it very difficult to navigate without better documentation. I did manage to make the tests run, but I'm not sure what code it was running. I would love to see the implementation details, and how this framework operates. 

In terms of starting the service itself and being able to make my own HTTP requests, I was unsuccessful.  The error I'm getting is at the bottom of this message.

I just think that you should stick with frameworks that were built on languages that handle web services better, such as python, js, and ruby. It is more familiar for everyone else, and ensures everything can be run effectively. 

(trusty)justin@localhost:~/Desktop/dataeng/hw2/RESTfulSkiPlanner$ ant ProdServer
Buildfile: /home/justin/Desktop/dataeng/hw2/RESTfulSkiPlanner/build.xml

ProdServer:
     [java] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/bshouse/wsdb/server/Servers : Unsupported major.minor version 52.0
     [java]     at java.lang.ClassLoader.defineClass1(Native Method)
     [java]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
     [java]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [java]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
     [java]     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [java]     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

BUILD FAILED
/home/justin/Desktop/dataeng/hw2/RESTfulSkiPlanner/build.xml:138: Java returned: 1

Total time: 1 second

**Comment by wderaad** [comment]
If you downloaded the repository before this message please re-download it before evaluating. The latest commit snuck in a bunch of class files so I reverted back to the previous commit and it is working the way it should.
